### ISSUE TITLE
In ".pcf.gz" format?

### ISSUE THREAD

**Issue by ianyepan** [yeyushengfan258/We10XOS-cursors#2]
As titled, I'd love to use your mouse cursor very much. However, my X11 system (WSL on Windows 10) only accepts cursor files in ".pcf.gz" format. Is there a way to convert your theme into such format?

**Comment by thexpand** [comment]
I am also interested in having them as a single file `cursor.pcf.gz`. Also, I'm using a 4K screen, so it would be better to have both a small and a large one. I'm not sure how to bundle them as a font. Otherwise I would be happy to do it if I knew how.

**Comment by yeyushengfan258** [comment]
Sorry, I don't know how to convert.

**Comment by thexpand** [comment]
I tried to find a solution for this. So far, the best one I can find is this here - https://github.com/charakterziffer/cursor-toolbox
But I don't have enough time to do the research about it and if we can use it for the job. What are your thoughts?

**Comment by yeyushengfan258** [comment]
I need time to learn.

**Comment by yeyushengfan258** [comment]
Thanks for the tip

**Comment by ianyepan** [comment]
@yeyushengfan258 I found a solution to use your theme without having to convert it to .pcf.gz format.

So it turns out I can extract the cursor theme under `~/.icons` and then in `.Xresources` put these lines:

```text
Xcursor.theme: We10XOS-cursors
Xcursor.size: 40
```

Then finally load it with `xrdb -merge ~/.Xresources`
