### ISSUE TITLE
Alternative cursors without shadows?

### ISSUE THREAD

**Issue by ianyepan** [yeyushengfan258/We10XOS-cursors#3]
Thanks for this amazing cursor theme -- can't believe I didn't start using earlier!
Is it possible to ask for an alternative cursor set without the shadows, just a personal preference request. Thanks again!

**Comment by yeyushengfan258** [comment]
No problem

**Comment by ianyepan** [comment]
Wow, you're so nice -- can't wait! Happy belated mid-autumn festival btw!

**Comment by yeyushengfan258** [comment]
Thank you.

**Comment by yeyushengfan258** [comment]
uploaded

**Comment by ianyepan** [comment]
Thanks so much! Works like a charm.
